apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- user-secret.yaml
- configmap.yaml
- subscription.yaml
- service-mapper-cluster-role.yaml
patches:
  - path: ./patches/user-secret.yaml
