apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: demo-soa-srm-sqs
rules:
- apiGroups:
  - "sqs.services.k8s.aws"
  resources:
  - "queues"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-soa-srm-sqs-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: demo-soa-srm-sqs
subjects:
- kind: ServiceAccount
  name: service-mapper-controller-manager
  namespace: service-mapper-system
