apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- queue.yaml
- queue-servicemapper.yaml
patchesJson6902:
  - target:
      group: sqs.services.k8s.aws
      version: v1alpha1
      kind: Queue
      name: demo-soa-sqs
    path: ./patches/sqs-policy.yaml
