apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - ../../base
  - ../../../infra/local/catalog-db
  - ../../../infra/local/orders-db
  - ../../../infra/local/queue
  - ../../../infra/local/catalog-identity
  - ../../../infra/local/orders-identity
  - ../../../infra/local/orders-events-consumer-identity
  - ../../../operators/service-binding-operator
