apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-binding-operator
  namespace: operators
spec:
  channel: stable
  name: service-binding-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: sbo-srm
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups:
  - "binding.operators.coreos.com"
  resources:
  - "serviceproxies"
  verbs:
  - get
  - list
  - watch

