apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: demo-soa-orders-db
spec:
  name: dynamodb
  service:
    apiVersion: v1
    kind: Secret
    name: orders-db-secret
  workload:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: demo-soa-orders
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: demo-soa-orders-aws
spec:
  name: aws
  service:
    apiVersion: v1
    kind: Secret
    name: orders-aws-client-secret
  workload:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: demo-soa-orders
