apiVersion: v1
kind: Secret
metadata:
  name: orders-aws-client-secret
  namespace: demo-soa
stringData:
  type: aws
  provider: aws
  access_key_id: dummy
  region: us-east-1
  secret_access_key: dummy
  session_token: dummy
  source: dummy
